# Generated by Django 5.1.3 on 2024-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("telegram_id", models.CharField(max_length=20, unique=True)),
                ("is_subscribed_group", models.BooleanField(default=False)),
                ("is_subscribed_channel", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TG-Пользователь",
                "verbose_name_plural": "TG-Пользователи",
                "ordering": ["-created_at"],
            },
        ),
    ]
