# Generated by Django 5.1.3 on 2024-11-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_subscribed_channel",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_subscribed_group",
        ),
    ]
