# Generated by Django 5.1.3 on 2024-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requiredchat",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="requiredchat",
            old_name="chat_type",
            new_name="type",
        ),
        migrations.AddField(
            model_name="requiredchat",
            name="url",
            field=models.URLField(default=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requiredchat",
            name="username",
            field=models.CharField(default=21, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
