# Generated by Django 5.1.3 on 2024-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_name_requiredchat_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requiredchat",
            name="url",
        ),
        migrations.AlterField(
            model_name="requiredchat",
            name="chat_id",
            field=models.CharField(max_length=255, unique=True, verbose_name="ID чата"),
        ),
        migrations.AlterField(
            model_name="requiredchat",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название чата"),
        ),
        migrations.AlterField(
            model_name="requiredchat",
            name="type",
            field=models.CharField(
                choices=[("group", "Группа"), ("channel", "Канал")],
                max_length=7,
                verbose_name="Тип чата",
            ),
        ),
        migrations.AlterField(
            model_name="requiredchat",
            name="username",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Никнейм чата"
            ),
        ),
    ]
