# Generated by Django 5.1.3 on 2024-11-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chats",
            "0003_remove_requiredchat_url_alter_requiredchat_chat_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="Вопрос"),
                ),
                ("answer", models.TextField(verbose_name="Ответ")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
            },
        ),
    ]
