# Generated by Django 5.1.3 on 2024-11-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("title",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
